/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRewardsIndexRouteImport } from './routes/api/rewards/index'
import { Route as ApiRewardsAddressRouteImport } from './routes/api/rewards/$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewardsIndexRoute = ApiRewardsIndexRouteImport.update({
  id: '/api/rewards/',
  path: '/api/rewards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewardsAddressRoute = ApiRewardsAddressRouteImport.update({
  id: '/api/rewards/$address',
  path: '/api/rewards/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rewards': typeof RewardsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rewards/$address': typeof ApiRewardsAddressRoute
  '/api/rewards/': typeof ApiRewardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rewards': typeof RewardsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rewards/$address': typeof ApiRewardsAddressRoute
  '/api/rewards': typeof ApiRewardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rewards': typeof RewardsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rewards/$address': typeof ApiRewardsAddressRoute
  '/api/rewards/': typeof ApiRewardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rewards'
    | '/api/auth/$'
    | '/api/rewards/$address'
    | '/api/rewards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rewards'
    | '/api/auth/$'
    | '/api/rewards/$address'
    | '/api/rewards'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/rewards'
    | '/api/auth/$'
    | '/api/rewards/$address'
    | '/api/rewards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RewardsRoute: typeof RewardsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRewardsAddressRoute: typeof ApiRewardsAddressRoute
  ApiRewardsIndexRoute: typeof ApiRewardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewards/': {
      id: '/api/rewards/'
      path: '/api/rewards'
      fullPath: '/api/rewards/'
      preLoaderRoute: typeof ApiRewardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewards/$address': {
      id: '/api/rewards/$address'
      path: '/api/rewards/$address'
      fullPath: '/api/rewards/$address'
      preLoaderRoute: typeof ApiRewardsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RewardsRoute: RewardsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRewardsAddressRoute: ApiRewardsAddressRoute,
  ApiRewardsIndexRoute: ApiRewardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
